---
- hosts: spock
  tasks:
    - name: build content locally
      make:
        chdir: "{{ lookup('env', 'PWD') }}"
        target: content
      delegate_to: localhost

    - name: copy content to the remote
      become: true
      copy:
        src: public/
        dest: /var/www/jchri.st/
